import { ReactNode } from 'react';
import './globals.css';
import { AuthProvider } from './context/AuthContext';

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <AuthProvider>
      <html lang="en">
        <head>
          <title>My Next.js App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </head>
        <body>
          {children}
        </body>
      </html>
    </AuthProvider>
  );
};

export default RootLayout;
