import { ReactNode } from 'react';
import './globals.css';
import { AuthProvider } from './context/AuthContext';
import {Providers} from './providers';

interface LayoutProps {
  children: ReactNode;
}

const RootLayout = ({ children }: LayoutProps) => {
  return (
    <AuthProvider>
        <html lang="en">
          <head>
            <title>My Next.js App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </head>
          <body>
            <Providers>
            {children}
            </Providers>
          </body>
        </html>
    </AuthProvider>
  );
};

export default RootLayout;
